export const REQUEST_ADD_TASK = 'REQUEST_ADD_TASK';
export const REQUEST_ADD_TASK_SUCCESS = 'REQUEST_ADD_TASK_SUCCESS';
export const REQUEST_ADD_TASK_ERROR = 'REQUEST_ADD_TASK_ERROR';

export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK';
export const REQUEST_DELETE_TASK_SUCCESS = 'REQUEST_DELETE_TASK_SUCCESS';
export const REQUEST_DELETE_TASK_ERROR = 'REQUEST_DELETE_TASK_ERROR';

export const REQUEST_UPDATE_TASK = 'REQUEST_UPDATE_TASK';
export const REQUEST_UPDATE_TASK_SUCCESS = 'REQUEST_UPDATE_TASK_SUCCESS';
export const REQUEST_UPDATE_TASK_ERROR = 'REQUEST_UPDATE_TASK_ERROR';

export const REQUEST_FETCH_TASK_LIST = 'REQUEST_FETCH_TASK_LIST';
export const REQUEST_FETCH_TASK_LIST_SUCCESS = 'REQUEST_FETCH_TASK_LIST_SUCCESS';
export const REQUEST_FETCH_TASK_LIST_ERROR = 'REQUEST_FETCH_TASK_LIST_ERROR';